export interface PriceZoneRef {
  town: string;
  district: string;
  province: string;
  zone: string; // official DMRE zone code, e.g. "1", "2", "3", "4", "5", "5A", "6", "7"
}

// Official DMRE zone codes used in SA petroleum product pricing.
// Zone 1 = coastal base (Cape Town, Durban, PE); higher numbers = further inland.
// Verify exact codes against the current DMRE schedule before use.
export const KNOWN_ZONE_CODES = [
  '1', '1A',
  '2', '2A',
  '3', '3A',
  '4', '4A',
  '5', '5A',
  '6', '6A',
  '7', '7A',
];

// SA towns mapped to approximate DMRE fuel price zone codes.
// Areas not listed (e.g. Ashton) fall under a nearby magisterial district (e.g. Montagu = zone 3).
// Always verify against the current DMRE "Petroleum Products Pricing" schedule.
export const PRICE_ZONE_REFS: PriceZoneRef[] = [
  // ── Western Cape – Zone 1 (Coastal base) ──
  { town: 'Cape Town', district: 'Cape Town', province: 'Western Cape', zone: '1' },
  { town: 'Bellville', district: 'Cape Town', province: 'Western Cape', zone: '1' },
  { town: 'Mitchells Plain', district: 'Cape Town', province: 'Western Cape', zone: '1' },
  { town: 'Khayelitsha', district: 'Cape Town', province: 'Western Cape', zone: '1' },
  { town: 'Stellenbosch', district: 'Stellenbosch', province: 'Western Cape', zone: '1' },
  { town: 'Franschhoek', district: 'Stellenbosch', province: 'Western Cape', zone: '1' },
  { town: 'Paarl', district: 'Paarl', province: 'Western Cape', zone: '1' },
  { town: 'Wellington', district: 'Paarl', province: 'Western Cape', zone: '1' },
  { town: 'Somerset West', district: 'Strand', province: 'Western Cape', zone: '1' },
  { town: 'Strand', district: 'Strand', province: 'Western Cape', zone: '1' },
  { town: "Gordon's Bay", district: 'Strand', province: 'Western Cape', zone: '1' },
  { town: 'Malmesbury', district: 'Malmesbury', province: 'Western Cape', zone: '1' },
  { town: 'Darling', district: 'Malmesbury', province: 'Western Cape', zone: '1' },
  { town: 'Moorreesburg', district: 'Malmesbury', province: 'Western Cape', zone: '1' },
  { town: 'Piketberg', district: 'Piketberg', province: 'Western Cape', zone: '1' },
  { town: 'Velddrif', district: 'Piketberg', province: 'Western Cape', zone: '1' },
  { town: 'Hopefield', district: 'Piketberg', province: 'Western Cape', zone: '1' },
  { town: 'Hermanus', district: 'Caledon', province: 'Western Cape', zone: '1' },
  { town: 'Caledon', district: 'Caledon', province: 'Western Cape', zone: '1' },
  { town: 'Grabouw', district: 'Caledon', province: 'Western Cape', zone: '2' },
  { town: 'Bredasdorp', district: 'Bredasdorp', province: 'Western Cape', zone: '1' },
  { town: 'Napier', district: 'Bredasdorp', province: 'Western Cape', zone: '1' },
  { town: 'Arniston', district: 'Bredasdorp', province: 'Western Cape', zone: '1' },
  { town: 'Swellendam', district: 'Swellendam', province: 'Western Cape', zone: '2' },
  { town: 'Barrydale', district: 'Swellendam', province: 'Western Cape', zone: '3' },
  { town: 'George', district: 'George', province: 'Western Cape', zone: '1' },
  { town: 'Wilderness', district: 'George', province: 'Western Cape', zone: '1' },
  { town: 'Knysna', district: 'Knysna', province: 'Western Cape', zone: '1' },
  { town: 'Plettenberg Bay', district: 'Knysna', province: 'Western Cape', zone: '1' },
  { town: 'Mossel Bay', district: 'Mossel Bay', province: 'Western Cape', zone: '1' },
  { town: 'Hartenbos', district: 'Mossel Bay', province: 'Western Cape', zone: '1' },
  { town: 'Stilbaai', district: 'Riversdale', province: 'Western Cape', zone: '1' },
  { town: 'Riversdale', district: 'Riversdale', province: 'Western Cape', zone: '1' },
  { town: 'Albertinia', district: 'Riversdale', province: 'Western Cape', zone: '2' },
  // ── Western Cape – Zone 2–3 (inland) ──
  { town: 'Worcester', district: 'Worcester', province: 'Western Cape', zone: '2' },
  { town: 'Rawsonville', district: 'Worcester', province: 'Western Cape', zone: '2' },
  { town: 'Robertson', district: 'Robertson', province: 'Western Cape', zone: '3' },
  { town: 'McGregor', district: 'Robertson', province: 'Western Cape', zone: '3' },
  { town: 'Ashton', district: 'Montagu', province: 'Western Cape', zone: '3' },
  { town: 'Montagu', district: 'Montagu', province: 'Western Cape', zone: '3' },
  { town: 'Bonnievale', district: 'Montagu', province: 'Western Cape', zone: '3' },
  { town: 'Ceres', district: 'Ceres', province: 'Western Cape', zone: '2' },
  { town: 'Tulbagh', district: 'Ceres', province: 'Western Cape', zone: '2' },
  { town: 'Wolseley', district: 'Ceres', province: 'Western Cape', zone: '2' },
  { town: 'Prince Alfred Hamlet', district: 'Ceres', province: 'Western Cape', zone: '3' },
  { town: 'Villiersdorp', district: 'Villiersdorp', province: 'Western Cape', zone: '2' },
  { town: 'Oudtshoorn', district: 'Oudtshoorn', province: 'Western Cape', zone: '3' },
  { town: 'De Rust', district: 'Oudtshoorn', province: 'Western Cape', zone: '3' },
  { town: 'Calitzdorp', district: 'Calitzdorp', province: 'Western Cape', zone: '3' },
  { town: 'Ladismith', district: 'Ladismith', province: 'Western Cape', zone: '3' },
  { town: 'Uniondale', district: 'Uniondale', province: 'Western Cape', zone: '4' },
  { town: 'Willowmore', district: 'Willowmore', province: 'Western Cape', zone: '5' },
  { town: 'Beaufort West', district: 'Beaufort West', province: 'Western Cape', zone: '5' },
  { town: 'Laingsburg', district: 'Laingsburg', province: 'Western Cape', zone: '4' },
  { town: 'Prince Albert', district: 'Prince Albert', province: 'Western Cape', zone: '4' },
  { town: 'Matjiesfontein', district: 'Laingsburg', province: 'Western Cape', zone: '4' },
  // ── Northern Cape ──
  { town: 'Springbok', district: 'Namaqualand', province: 'Northern Cape', zone: '1' },
  { town: 'Port Nolloth', district: 'Namaqualand', province: 'Northern Cape', zone: '1' },
  { town: 'Garies', district: 'Namaqualand', province: 'Northern Cape', zone: '2' },
  { town: 'Calvinia', district: 'Calvinia', province: 'Northern Cape', zone: '4' },
  { town: 'Carnarvon', district: 'Carnarvon', province: 'Northern Cape', zone: '5' },
  { town: 'Victoria West', district: 'Victoria West', province: 'Northern Cape', zone: '5' },
  { town: 'De Aar', district: 'De Aar', province: 'Northern Cape', zone: '5' },
  { town: 'Britstown', district: 'Britstown', province: 'Northern Cape', zone: '5' },
  { town: 'Prieska', district: 'Prieska', province: 'Northern Cape', zone: '5' },
  { town: 'Douglas', district: 'Douglas', province: 'Northern Cape', zone: '5' },
  { town: 'Kimberley', district: 'Kimberley', province: 'Northern Cape', zone: '6' },
  { town: 'Upington', district: 'Gordonia', province: 'Northern Cape', zone: '5A' },
  { town: 'Postmasburg', district: 'Postmasburg', province: 'Northern Cape', zone: '6' },
  { town: 'Kuruman', district: 'Kuruman', province: 'Northern Cape', zone: '6' },
  { town: 'Kathu', district: 'Kuruman', province: 'Northern Cape', zone: '6' },
  // ── Eastern Cape ──
  { town: 'Gqeberha', district: 'Port Elizabeth', province: 'Eastern Cape', zone: '1' },
  { town: 'Port Elizabeth', district: 'Port Elizabeth', province: 'Eastern Cape', zone: '1' },
  { town: 'Uitenhage', district: 'Uitenhage', province: 'Eastern Cape', zone: '1' },
  { town: 'Despatch', district: 'Uitenhage', province: 'Eastern Cape', zone: '1' },
  { town: 'East London', district: 'East London', province: 'Eastern Cape', zone: '1' },
  { town: "King William's Town", district: "King William's Town", province: 'Eastern Cape', zone: '1' },
  { town: 'Makhanda', district: 'Albany', province: 'Eastern Cape', zone: '1' },
  { town: 'Grahamstown', district: 'Albany', province: 'Eastern Cape', zone: '1' },
  { town: 'Port Alfred', district: 'Albany', province: 'Eastern Cape', zone: '1' },
  { town: 'Humansdorp', district: 'Humansdorp', province: 'Eastern Cape', zone: '1' },
  { town: 'Jeffreys Bay', district: 'Humansdorp', province: 'Eastern Cape', zone: '1' },
  { town: 'Butterworth', district: 'Butterworth', province: 'Eastern Cape', zone: '1' },
  { town: 'Bisho', district: "King William's Town", province: 'Eastern Cape', zone: '1' },
  { town: 'Alice', district: 'Victoria East', province: 'Eastern Cape', zone: '2' },
  { town: 'Mthatha', district: 'Mthatha', province: 'Eastern Cape', zone: '3' },
  { town: 'Komani', district: 'Queenstown', province: 'Eastern Cape', zone: '3' },
  { town: 'Queenstown', district: 'Queenstown', province: 'Eastern Cape', zone: '3' },
  { town: 'Fort Beaufort', district: 'Fort Beaufort', province: 'Eastern Cape', zone: '2' },
  { town: 'Somerset East', district: 'Somerset East', province: 'Eastern Cape', zone: '3' },
  { town: 'Steytlerville', district: 'Steytlerville', province: 'Eastern Cape', zone: '3' },
  { town: 'Tarkastad', district: 'Tarkastad', province: 'Eastern Cape', zone: '3' },
  { town: 'Elliot', district: 'Elliot', province: 'Eastern Cape', zone: '3' },
  { town: 'Engcobo', district: 'Engcobo', province: 'Eastern Cape', zone: '3' },
  { town: 'Graaff-Reinet', district: 'Graaff-Reinet', province: 'Eastern Cape', zone: '4' },
  { town: 'Cradock', district: 'Cradock', province: 'Eastern Cape', zone: '4' },
  { town: 'Middelburg (EC)', district: 'Middelburg', province: 'Eastern Cape', zone: '5' },
  { town: 'Aliwal North', district: 'Aliwal North', province: 'Eastern Cape', zone: '5' },
  { town: 'Burgersdorp', district: 'Burgersdorp', province: 'Eastern Cape', zone: '5' },
  { town: 'Barkly East', district: 'Barkly East', province: 'Eastern Cape', zone: '5' },
  { town: 'Lady Grey', district: 'Lady Grey', province: 'Eastern Cape', zone: '5' },
  // ── KwaZulu-Natal ──
  { town: 'Durban', district: 'Durban', province: 'KwaZulu-Natal', zone: '1' },
  { town: 'eThekwini', district: 'Durban', province: 'KwaZulu-Natal', zone: '1' },
  { town: 'Pinetown', district: 'Pinetown', province: 'KwaZulu-Natal', zone: '1' },
  { town: 'Amanzimtoti', district: 'Durban', province: 'KwaZulu-Natal', zone: '1' },
  { town: 'Umhlanga', district: 'Durban', province: 'KwaZulu-Natal', zone: '1' },
  { town: 'Ballito', district: 'Stanger', province: 'KwaZulu-Natal', zone: '1' },
  { town: 'Stanger', district: 'Stanger', province: 'KwaZulu-Natal', zone: '1' },
  { town: 'Richards Bay', district: 'Empangeni', province: 'KwaZulu-Natal', zone: '1' },
  { town: 'Empangeni', district: 'Empangeni', province: 'KwaZulu-Natal', zone: '1' },
  { town: 'Pietermaritzburg', district: 'Pietermaritzburg', province: 'KwaZulu-Natal', zone: '2' },
  { town: 'Port Shepstone', district: 'Port Shepstone', province: 'KwaZulu-Natal', zone: '1' },
  { town: 'Margate', district: 'Port Shepstone', province: 'KwaZulu-Natal', zone: '1' },
  { town: 'Howick', district: 'Lions River', province: 'KwaZulu-Natal', zone: '3' },
  { town: 'Kokstad', district: 'Kokstad', province: 'KwaZulu-Natal', zone: '3' },
  { town: 'Ulundi', district: 'Nongoma', province: 'KwaZulu-Natal', zone: '3' },
  { town: 'Nongoma', district: 'Nongoma', province: 'KwaZulu-Natal', zone: '3' },
  { town: 'Greytown', district: 'Greytown', province: 'KwaZulu-Natal', zone: '3' },
  { town: 'Newcastle', district: 'Newcastle', province: 'KwaZulu-Natal', zone: '5' },
  { town: 'Ladysmith', district: 'Ladysmith', province: 'KwaZulu-Natal', zone: '4' },
  { town: 'Estcourt', district: 'Estcourt', province: 'KwaZulu-Natal', zone: '4' },
  { town: 'Dundee', district: 'Dundee', province: 'KwaZulu-Natal', zone: '5' },
  { town: 'Glencoe', district: 'Dundee', province: 'KwaZulu-Natal', zone: '5' },
  { town: 'Vryheid', district: 'Vryheid', province: 'KwaZulu-Natal', zone: '5' },
  { town: 'Bergville', district: 'Bergville', province: 'KwaZulu-Natal', zone: '5' },
  // ── Free State ──
  { town: 'Bloemfontein', district: 'Bloemfontein', province: 'Free State', zone: '6' },
  { town: 'Mangaung', district: 'Bloemfontein', province: 'Free State', zone: '6' },
  { town: 'Welkom', district: 'Welkom', province: 'Free State', zone: '6' },
  { town: 'Virginia', district: 'Welkom', province: 'Free State', zone: '6' },
  { town: 'Odendaalsrus', district: 'Welkom', province: 'Free State', zone: '6' },
  { town: 'Kroonstad', district: 'Kroonstad', province: 'Free State', zone: '6' },
  { town: 'Sasolburg', district: 'Sasolburg', province: 'Free State', zone: '6' },
  { town: 'Parys', district: 'Parys', province: 'Free State', zone: '6' },
  { town: 'Harrismith', district: 'Harrismith', province: 'Free State', zone: '5' },
  { town: 'Bethlehem', district: 'Bethlehem', province: 'Free State', zone: '5' },
  { town: 'Phuthaditjhaba', district: 'Qwaqwa', province: 'Free State', zone: '5' },
  { town: 'Zastron', district: 'Zastron', province: 'Free State', zone: '5' },
  { town: 'Ladybrand', district: 'Ladybrand', province: 'Free State', zone: '6' },
  { town: 'Ficksburg', district: 'Ficksburg', province: 'Free State', zone: '5' },
  { town: 'Senekal', district: 'Senekal', province: 'Free State', zone: '6' },
  { town: 'Frankfort', district: 'Frankfort', province: 'Free State', zone: '6' },
  { town: 'Vrede', district: 'Vrede', province: 'Free State', zone: '6' },
  // ── Gauteng – Zone 7 ──
  { town: 'Johannesburg', district: 'Johannesburg', province: 'Gauteng', zone: '7' },
  { town: 'Sandton', district: 'Johannesburg', province: 'Gauteng', zone: '7' },
  { town: 'Soweto', district: 'Johannesburg', province: 'Gauteng', zone: '7' },
  { town: 'Roodepoort', district: 'Johannesburg', province: 'Gauteng', zone: '7' },
  { town: 'Randburg', district: 'Johannesburg', province: 'Gauteng', zone: '7' },
  { town: 'Midrand', district: 'Johannesburg', province: 'Gauteng', zone: '7' },
  { town: 'Pretoria', district: 'Pretoria', province: 'Gauteng', zone: '7' },
  { town: 'Tshwane', district: 'Pretoria', province: 'Gauteng', zone: '7' },
  { town: 'Centurion', district: 'Pretoria', province: 'Gauteng', zone: '7' },
  { town: 'Soshanguve', district: 'Pretoria', province: 'Gauteng', zone: '7' },
  { town: 'Mamelodi', district: 'Pretoria', province: 'Gauteng', zone: '7' },
  { town: 'Germiston', district: 'Germiston', province: 'Gauteng', zone: '7' },
  { town: 'Ekurhuleni', district: 'Germiston', province: 'Gauteng', zone: '7' },
  { town: 'Boksburg', district: 'Germiston', province: 'Gauteng', zone: '7' },
  { town: 'Benoni', district: 'Benoni', province: 'Gauteng', zone: '7' },
  { town: 'Brakpan', district: 'Brakpan', province: 'Gauteng', zone: '7' },
  { town: 'Springs', district: 'Springs', province: 'Gauteng', zone: '7' },
  { town: 'Alberton', district: 'Alberton', province: 'Gauteng', zone: '7' },
  { town: 'Krugersdorp', district: 'Krugersdorp', province: 'Gauteng', zone: '7' },
  { town: 'Randfontein', district: 'Randfontein', province: 'Gauteng', zone: '7' },
  { town: 'Westonaria', district: 'Westonaria', province: 'Gauteng', zone: '7' },
  { town: 'Vereeniging', district: 'Vereeniging', province: 'Gauteng', zone: '7' },
  { town: 'Vanderbijlpark', district: 'Vereeniging', province: 'Gauteng', zone: '7' },
  { town: 'Evaton', district: 'Vereeniging', province: 'Gauteng', zone: '7' },
  // ── North West ──
  { town: 'Rustenburg', district: 'Rustenburg', province: 'North West', zone: '7' },
  { town: 'Potchefstroom', district: 'Potchefstroom', province: 'North West', zone: '7' },
  { town: 'Brits', district: 'Brits', province: 'North West', zone: '7' },
  { town: 'Hartbeespoort', district: 'Brits', province: 'North West', zone: '7' },
  { town: 'Ventersdorp', district: 'Ventersdorp', province: 'North West', zone: '7' },
  { town: 'Klerksdorp', district: 'Klerksdorp', province: 'North West', zone: '6' },
  { town: 'Orkney', district: 'Klerksdorp', province: 'North West', zone: '6' },
  { town: 'Mahikeng', district: 'Mafikeng', province: 'North West', zone: '6' },
  { town: 'Mafikeng', district: 'Mafikeng', province: 'North West', zone: '6' },
  { town: 'Lichtenburg', district: 'Lichtenburg', province: 'North West', zone: '6' },
  { town: 'Zeerust', district: 'Zeerust', province: 'North West', zone: '6' },
  { town: 'Wolmaransstad', district: 'Wolmaransstad', province: 'North West', zone: '6' },
  // ── Limpopo ──
  { town: 'Polokwane', district: 'Pietersburg', province: 'Limpopo', zone: '7' },
  { town: 'Mokopane', district: 'Potgietersrus', province: 'Limpopo', zone: '7' },
  { town: 'Bela-Bela', district: 'Warmbad', province: 'Limpopo', zone: '7' },
  { town: 'Makhado', district: 'Louis Trichardt', province: 'Limpopo', zone: '7' },
  { town: 'Louis Trichardt', district: 'Louis Trichardt', province: 'Limpopo', zone: '7' },
  { town: 'Musina', district: 'Soutpansberg', province: 'Limpopo', zone: '7' },
  { town: 'Tzaneen', district: 'Tzaneen', province: 'Limpopo', zone: '7' },
  { town: 'Lephalale', district: 'Ellisras', province: 'Limpopo', zone: '7' },
  { town: 'Phalaborwa', district: 'Phalaborwa', province: 'Limpopo', zone: '7' },
  { town: 'Giyani', district: 'Giyani', province: 'Limpopo', zone: '7' },
  { town: 'Thohoyandou', district: 'Vuwani', province: 'Limpopo', zone: '7' },
  { town: 'Burgersfort', district: 'Lydenburg', province: 'Limpopo', zone: '7' },
  { town: 'Marble Hall', district: 'Marble Hall', province: 'Limpopo', zone: '7' },
  { town: 'Modimolle', district: 'Nylstroom', province: 'Limpopo', zone: '7' },
  // ── Mpumalanga ──
  { town: 'Mbombela', district: 'Nelspruit', province: 'Mpumalanga', zone: '4' },
  { town: 'Nelspruit', district: 'Nelspruit', province: 'Mpumalanga', zone: '4' },
  { town: 'White River', district: 'Nelspruit', province: 'Mpumalanga', zone: '4' },
  { town: 'Hazyview', district: 'Nelspruit', province: 'Mpumalanga', zone: '4' },
  { town: 'Komatipoort', district: 'Komatipoort', province: 'Mpumalanga', zone: '3' },
  { town: 'Barberton', district: 'Barberton', province: 'Mpumalanga', zone: '4' },
  { town: 'Lydenburg', district: 'Lydenburg', province: 'Mpumalanga', zone: '5' },
  { town: 'Standerton', district: 'Standerton', province: 'Mpumalanga', zone: '6' },
  { town: 'Ermelo', district: 'Ermelo', province: 'Mpumalanga', zone: '6' },
  { town: 'Carolina', district: 'Carolina', province: 'Mpumalanga', zone: '6' },
  { town: 'Piet Retief', district: 'Piet Retief', province: 'Mpumalanga', zone: '5' },
  { town: 'Volksrust', district: 'Volksrust', province: 'Mpumalanga', zone: '6' },
  { town: 'eMalahleni', district: 'Witbank', province: 'Mpumalanga', zone: '7' },
  { town: 'Witbank', district: 'Witbank', province: 'Mpumalanga', zone: '7' },
  { town: 'Middelburg (MP)', district: 'Middelburg', province: 'Mpumalanga', zone: '7' },
  { town: 'Secunda', district: 'Secunda', province: 'Mpumalanga', zone: '7' },
  { town: 'Evander', district: 'Evander', province: 'Mpumalanga', zone: '7' },
  { town: 'Balfour', district: 'Balfour', province: 'Mpumalanga', zone: '7' },
  { town: 'Bethal', district: 'Bethal', province: 'Mpumalanga', zone: '7' },
];

export function lookupZone(townOrDistrict: string): PriceZoneRef | null {
  const q = townOrDistrict.trim().toLowerCase();
  return (
    PRICE_ZONE_REFS.find(r => r.town.toLowerCase() === q || r.district.toLowerCase() === q) ?? null
  );
}

export function downloadZoneReference(): void {
  const header = 'Town/Area,Magisterial District,Province,DMRE Zone Code\n';
  const rows = PRICE_ZONE_REFS.map(r =>
    `"${r.town}","${r.district}","${r.province}","${r.zone}"`
  ).join('\n');
  const blob = new Blob([header + rows], { type: 'text/csv' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = 'sa_dmre_fuel_price_zones_reference.csv';
  a.click();
  URL.revokeObjectURL(url);
}
