export interface PriceZoneRef {
  town: string;
  district: string;
  province: string;
  zone: string; // official DMRE magisterial district zone code, e.g. "01A", "09C", "57A"
}

// All unique DMRE zone codes extracted from the official magisterial district zone schedule.
export const KNOWN_ZONE_CODES = [
  '01A', '02A', '03A', '03B', '03C',
  '04A', '04C',
  '05A', '05B', '05C',
  '06A', '06B', '06C',
  '07A', '07B', '07C',
  '08A', '08B', '08C',
  '09A', '09B', '09C',
  '10B', '10C',
  '11A', '11C',
  '12B', '12C',
  '13A', '13C',
  '14B', '14C',
  '15A', '15C',
  '16C',
  '17A', '17C',
  '19A',
  '31J', '32J', '33J', '34J', '35J', '36J', '37J',
  '57A', '57C',
  '58C',
  '60C', '61C', '62C', '63C', '64C',
  '67C',
  '69A',
];

// Official DMRE magisterial district zone reference.
// Source: ufuel.co.za/knowledge-centre/fuel-zones (based on DMRE petroleum pricing schedule).
export const PRICE_ZONE_REFS: PriceZoneRef[] = [
  { town: 'Aberdeen', district: 'Aberdeen', province: 'Eastern Cape', zone: '09B' },
  { town: 'Adelaide', district: 'Adelaide', province: 'Eastern Cape', zone: '05A' },
  { town: 'Albany', district: 'Albany', province: 'Eastern Cape', zone: '04A' },
  { town: 'Albert', district: 'Albert', province: 'Eastern Cape', zone: '07A' },
  { town: 'Alberton', district: 'Alberton', province: 'Gauteng', zone: '09C' },
  { town: 'Alexandria', district: 'Alexandria', province: 'Eastern Cape', zone: '04A' },
  { town: 'Alfred', district: 'Alfred', province: 'KwaZulu-Natal', zone: '05A' },
  { town: 'Aliwal North', district: 'Aliwal North', province: 'Eastern Cape', zone: '07A' },
  { town: 'Amersfoort', district: 'Amersfoort', province: 'Mpumalanga', zone: '08C' },
  { town: 'Babanango', district: 'Babanango', province: 'KwaZulu-Natal', zone: '06A' },
  { town: 'Bafokeng', district: 'Bafokeng', province: 'North West', zone: '09C' },
  { town: 'Balfour', district: 'Balfour', province: 'Mpumalanga', zone: '09C' },
  { town: 'Barberton', district: 'Barberton', province: 'Mpumalanga', zone: '61C' },
  { town: 'Barkly East', district: 'Barkly East', province: 'Eastern Cape', zone: '08A' },
  { town: 'Barkly West', district: 'Barkly West', province: 'Northern Cape', zone: '11C' },
  { town: 'Bathurst', district: 'Bathurst (Port Alfred)', province: 'Eastern Cape', zone: '05A' },
  { town: 'Port Alfred', district: 'Bathurst (Port Alfred)', province: 'Eastern Cape', zone: '05A' },
  { town: 'Beaufort West', district: 'Beaufort West', province: 'Western Cape', zone: '08B' },
  { town: 'Bedford', district: 'Bedford', province: 'Eastern Cape', zone: '05A' },
  { town: 'Bela-Bela', district: 'Bela-Bela (Warmbad)', province: 'Limpopo', zone: '10C' },
  { town: 'Warmbad', district: 'Bela-Bela (Warmbad)', province: 'Limpopo', zone: '10C' },
  { town: 'Belfast', district: 'Belfast', province: 'Mpumalanga', zone: '10C' },
  { town: 'Bellville', district: 'Bellville', province: 'Western Cape', zone: '01A' },
  { town: 'Benoni', district: 'Benoni', province: 'Gauteng', zone: '09C' },
  { town: 'Bergville', district: 'Bergville', province: 'KwaZulu-Natal', zone: '06C' },
  { town: 'Bethal', district: 'Bethal', province: 'Mpumalanga', zone: '09C' },
  { town: 'Bethlehem', district: 'Bethlehem', province: 'Free State', zone: '07C' },
  { town: 'Bethulie', district: 'Bethulie', province: 'Free State', zone: '08A' },
  { town: 'Bizana', district: 'Bizana', province: 'Eastern Cape', zone: '09B' },
  { town: 'Bloemfontein', district: 'Bloemfontein', province: 'Free State', zone: '11C' },
  { town: 'Mangaung', district: 'Bloemfontein', province: 'Free State', zone: '11C' },
  { town: 'Bloemhof', district: 'Bloemhof', province: 'North West', zone: '10C' },
  { town: 'Bochum', district: 'Bochum', province: 'Limpopo', zone: '13C' },
  { town: 'Boksburg', district: 'Boksburg', province: 'Gauteng', zone: '09C' },
  { town: 'Bolobedu', district: 'Bolobedu', province: 'Limpopo', zone: '63C' },
  { town: 'Boshof', district: 'Boshof', province: 'Free State', zone: '11C' },
  { town: 'Bothaville', district: 'Bothaville', province: 'Free State', zone: '09C' },
  { town: 'Botshabelo', district: 'Botshabelo', province: 'Free State', zone: '11C' },
  { town: 'Brakpan', district: 'Brakpan', province: 'Gauteng', zone: '09C' },
  { town: 'Brandfort', district: 'Brandfort', province: 'Free State', zone: '10C' },
  { town: 'Bredasdorp', district: 'Bredasdorp', province: 'Western Cape', zone: '06A' },
  { town: 'Brits', district: 'Brits', province: 'North West', zone: '09C' },
  { town: 'Britstown', district: 'Britstown', province: 'Northern Cape', zone: '09A' },
  { town: 'Bronkhorstspruit', district: 'Bronkhorstspruit', province: 'Gauteng', zone: '09C' },
  { town: 'Bultfontein', district: 'Bultfontein', province: 'Free State', zone: '10C' },
  { town: 'Caledon', district: 'Caledon', province: 'Western Cape', zone: '05A' },
  { town: 'Calitzdorp', district: 'Calitzdorp', province: 'Western Cape', zone: '04A' },
  { town: 'Calvinia', district: 'Calvinia', province: 'Northern Cape', zone: '12B' },
  { town: 'Camperdown', district: 'Camperdown', province: 'KwaZulu-Natal', zone: '02A' },
  { town: 'Cape Town', district: 'Cape Town', province: 'Western Cape', zone: '01A' },
  { town: 'Carnarvon', district: 'Carnavon', province: 'Northern Cape', zone: '10B' },
  { town: 'Carolina', district: 'Carolina', province: 'Mpumalanga', zone: '10C' },
  { town: 'Cathcart', district: 'Cathcart', province: 'Eastern Cape', zone: '05A' },
  { town: 'Centane', district: 'Centane', province: 'Eastern Cape', zone: '05A' },
  { town: 'Ceres', district: 'Ceres', province: 'Western Cape', zone: '05A' },
  { town: 'Chatsworth', district: 'Chatsworth', province: 'KwaZulu-Natal', zone: '01A' },
  { town: 'Christiana', district: 'Christiana', province: 'North West', zone: '10C' },
  { town: 'Clanwilliam', district: 'Clanwilliam', province: 'Western Cape', zone: '07B' },
  { town: 'Clocolan', district: 'Clocolan', province: 'Free State', zone: '08C' },
  { town: 'Cofimvaba', district: 'Cofimvaba (St Marks)', province: 'Eastern Cape', zone: '05A' },
  { town: 'Colesberg', district: 'Colesberg', province: 'Northern Cape', zone: '08A' },
  { town: 'Coligny', district: 'Coligny', province: 'North West', zone: '10C' },
  { town: 'Cradock', district: 'Cradock', province: 'Eastern Cape', zone: '08B' },
  { town: 'Cullinan', district: 'Cullinan', province: 'Gauteng', zone: '09C' },
  { town: 'Dannhauser', district: 'Dannhauser', province: 'KwaZulu-Natal', zone: '06C' },
  { town: 'De Aar', district: 'De Aar', province: 'Northern Cape', zone: '08A' },
  { town: 'Delareyville', district: 'Delareyville', province: 'North West', zone: '11C' },
  { town: 'Delmas', district: 'Delmas', province: 'Mpumalanga', zone: '09C' },
  { town: 'Dewetsdorp', district: 'Dewetsdorp', province: 'Free State', zone: '11C' },
  { town: 'Ditsobotla', district: 'Ditsobotla', province: 'North West', zone: '12C' },
  { town: 'Dundee', district: 'Dundee', province: 'KwaZulu-Natal', zone: '06C' },
  { town: 'Durban', district: 'Durban', province: 'KwaZulu-Natal', zone: '01A' },
  { town: 'eThekwini', district: 'Durban', province: 'KwaZulu-Natal', zone: '01A' },
  { town: 'East London', district: 'East London', province: 'Eastern Cape', zone: '01A' },
  { town: 'Edenburg', district: 'Edenburg', province: 'Free State', zone: '08A' },
  { town: 'Eerstehoek', district: 'Eerstehoek', province: 'Mpumalanga', zone: '10C' },
  { town: 'Elliot', district: 'Elliot', province: 'Eastern Cape', zone: '08A' },
  { town: 'Engcobo', district: 'Engcobo', province: 'Eastern Cape', zone: '57A' },
  { town: 'Ermelo', district: 'Ermelo', province: 'Mpumalanga', zone: '08C' },
  { town: 'Eshowe', district: 'Eshowe', province: 'KwaZulu-Natal', zone: '04A' },
  { town: 'Estcourt', district: 'Estcourt', province: 'KwaZulu-Natal', zone: '05B' },
  { town: 'Excelsior', district: 'Excelsior', province: 'Free State', zone: '10C' },
  { town: 'Fauresmith', district: 'Fauresmith', province: 'Free State', zone: '09A' },
  { town: 'Ficksburg', district: 'Ficksburg', province: 'Free State', zone: '08C' },
  { town: 'Fort Beaufort', district: 'Fort Beaufort', province: 'Eastern Cape', zone: '05A' },
  { town: 'Fouriesburg', district: 'Fouriesburg', province: 'Free State', zone: '07C' },
  { town: 'Frankfort', district: 'Frankfort', province: 'Free State', zone: '08C' },
  { town: 'Fraserburg', district: 'Fraserburg', province: 'Northern Cape', zone: '08B' },
  { town: 'Ganyesa', district: 'Ganyesa', province: 'North West', zone: '15C' },
  { town: 'Gatyana', district: 'Gatyana (Willowvale)', province: 'Eastern Cape', zone: '05A' },
  { town: 'Willowvale', district: 'Gatyana (Willowvale)', province: 'Eastern Cape', zone: '05A' },
  { town: 'Butterworth', district: 'Gcuwa (Butterworth)', province: 'Eastern Cape', zone: '05A' },
  { town: 'George', district: 'George', province: 'Western Cape', zone: '03A' },
  { town: 'Germiston', district: 'Germiston', province: 'Gauteng', zone: '09C' },
  { town: 'Ekurhuleni', district: 'Germiston', province: 'Gauteng', zone: '09C' },
  { town: 'Giyani', district: 'Giyani', province: 'Limpopo', zone: '64C' },
  { town: 'Glencoe', district: 'Glencoe', province: 'KwaZulu-Natal', zone: '06C' },
  { town: 'Goodwood', district: 'Goodwood', province: 'Western Cape', zone: '01A' },
  { town: 'Gordonia', district: 'Gordonia', province: 'Northern Cape', zone: '13A' },
  { town: 'Upington', district: 'Gordonia', province: 'Northern Cape', zone: '13A' },
  { town: 'Graaff-Reinet', district: 'Graaff-Reinet', province: 'Eastern Cape', zone: '09B' },
  { town: 'Groblersdal', district: 'Groblersdal', province: 'Mpumalanga', zone: '10C' },
  { town: 'Hankey', district: 'Hankey', province: 'Eastern Cape', zone: '03A' },
  { town: 'Hanover', district: 'Hanover', province: 'Northern Cape', zone: '08A' },
  { town: 'Harrismith', district: 'Harrismith', province: 'Free State', zone: '06C' },
  { town: 'Hartswater', district: 'Hartswater', province: 'Northern Cape', zone: '11C' },
  { town: 'Hay', district: 'Hay', province: 'Northern Cape', zone: '11A' },
  { town: 'Heidelberg', district: 'Heidelberg (Gauteng)', province: 'Gauteng', zone: '09C' },
  { town: 'Heilbron', district: 'Heilbron', province: 'Free State', zone: '08C' },
  { town: 'Hennenman', district: 'Hennenman', province: 'Free State', zone: '09C' },
  { town: 'Herbert', district: 'Herbert', province: 'Northern Cape', zone: '11C' },
  { town: 'Hermanus', district: 'Hermanus', province: 'Western Cape', zone: '05A' },
  { town: 'Herschel', district: 'Herschel (Sterkspruit)', province: 'Eastern Cape', zone: '08A' },
  { town: 'Sterkspruit', district: 'Herschel (Sterkspruit)', province: 'Eastern Cape', zone: '08A' },
  { town: 'Highveld Ridge', district: 'Highveld Ridge', province: 'Mpumalanga', zone: '09C' },
  { town: 'Hlabisa', district: 'Hlabisa', province: 'KwaZulu-Natal', zone: '05A' },
  { town: 'Hofmeyer', district: 'Hofmeyer', province: 'Eastern Cape', zone: '57A' },
  { town: 'Hoopstad', district: 'Hoopstad', province: 'Free State', zone: '10C' },
  { town: 'Hopefield', district: 'Hopefield', province: 'Western Cape', zone: '05A' },
  { town: 'Hopetown', district: 'Hopetown', province: 'Northern Cape', zone: '09A' },
  { town: 'Humansdorp', district: 'Humansdorp', province: 'Eastern Cape', zone: '03B' },
  { town: 'Jeffreys Bay', district: 'Humansdorp', province: 'Eastern Cape', zone: '03B' },
  { town: 'Impendle', district: 'Impendle', province: 'KwaZulu-Natal', zone: '05B' },
  { town: 'Inanda', district: 'Inanda', province: 'KwaZulu-Natal', zone: '01A' },
  { town: 'Indwe', district: 'Indwe', province: 'Eastern Cape', zone: '57A' },
  { town: 'Ingwavuma', district: 'Ingwavuma', province: 'KwaZulu-Natal', zone: '57A' },
  { town: 'Ixopo', district: 'Ixopo', province: 'KwaZulu-Natal', zone: '04A' },
  { town: 'Jacobsdal', district: 'Jacobsdal', province: 'Free State', zone: '11C' },
  { town: 'Jagersfontein', district: 'Jagersfontein', province: 'Free State', zone: '08A' },
  { town: 'Jansenville', district: 'Jansenville', province: 'Eastern Cape', zone: '07B' },
  { town: 'Johannesburg', district: 'Johannesburg', province: 'Gauteng', zone: '09C' },
  { town: 'Sandton', district: 'Johannesburg', province: 'Gauteng', zone: '09C' },
  { town: 'Soweto', district: 'Johannesburg', province: 'Gauteng', zone: '09C' },
  { town: 'Randburg', district: 'Johannesburg', province: 'Gauteng', zone: '09C' },
  { town: 'Joubertina', district: 'Joubertina', province: 'Eastern Cape', zone: '07B' },
  { town: 'Keiskammahoek', district: 'Keiskammahoek', province: 'Eastern Cape', zone: '04A' },
  { town: 'Kempton Park', district: 'Kempton Park', province: 'Gauteng', zone: '09C' },
  { town: 'Kenhardt', district: 'Kenhardt', province: 'Northern Cape', zone: '15A' },
  { town: 'Kimberley', district: 'Kimberley', province: 'Northern Cape', zone: '11C' },
  { town: 'King William\'s Town', district: 'King Williams Town', province: 'Eastern Cape', zone: '03A' },
  { town: 'Kirkwood', district: 'Kirkwood', province: 'Eastern Cape', zone: '03A' },
  { town: 'Klerksdorp', district: 'Klerksdorp', province: 'North West', zone: '09C' },
  { town: 'Kliprivier', district: 'Kliprivier', province: 'KwaZulu-Natal', zone: '05C' },
  { town: 'Knysna', district: 'Knysna', province: 'Western Cape', zone: '04A' },
  { town: 'Plettenberg Bay', district: 'Knysna', province: 'Western Cape', zone: '04A' },
  { town: 'Koffiefontein', district: 'Koffiefontein', province: 'Free State', zone: '09A' },
  { town: 'Komga', district: 'Komga', province: 'Eastern Cape', zone: '03A' },
  { town: 'Koppies', district: 'Koppies', province: 'Free State', zone: '09C' },
  { town: 'Koster', district: 'Koster', province: 'North West', zone: '09C' },
  { town: 'Kranskop', district: 'Kranskop', province: 'KwaZulu-Natal', zone: '05A' },
  { town: 'Kriel', district: 'Kriel', province: 'Mpumalanga', zone: '09C' },
  { town: 'Kroonstad', district: 'Kroonstad', province: 'Free State', zone: '09C' },
  { town: 'Krugersdorp', district: 'Krugersdorp', province: 'Gauteng', zone: '09C' },
  { town: 'Kudumane', district: 'Kudumane', province: 'North West', zone: '15C' },
  { town: 'Kuilsrivier', district: 'Kuilsrivier', province: 'Western Cape', zone: '01A' },
  { town: 'Kuruman', district: 'Kuruman', province: 'Northern Cape', zone: '13C' },
  { town: 'Kathu', district: 'Kuruman', province: 'Northern Cape', zone: '13C' },
  { town: 'Ladismith', district: 'Ladismith (Cape)', province: 'Western Cape', zone: '06B' },
  { town: 'Lady Grey', district: 'Lady Grey', province: 'Eastern Cape', zone: '08A' },
  { town: 'Ladybrand', district: 'Ladybrand', province: 'Free State', zone: '08C' },
  { town: 'Laingsburg', district: 'Laingsburg', province: 'Western Cape', zone: '07B' },
  { town: 'Lehurutshe', district: 'Lehurutshe', province: 'North West', zone: '11C' },
  { town: 'Lephalale', district: 'Lephalale (Ellisras)', province: 'Limpopo', zone: '13C' },
  { town: 'Ellisras', district: 'Lephalale (Ellisras)', province: 'Limpopo', zone: '13C' },
  { town: 'Letaba', district: 'Letaba', province: 'Limpopo', zone: '63C' },
  { town: 'Tzaneen', district: 'Letaba', province: 'Limpopo', zone: '63C' },
  { town: 'Lichtenburg', district: 'Lichtenburg', province: 'North West', zone: '10C' },
  { town: 'Lindley', district: 'Lindley', province: 'Free State', zone: '08C' },
  { town: 'Lions River', district: 'Lions River', province: 'KwaZulu-Natal', zone: '03B' },
  { town: 'Howick', district: 'Lions River', province: 'KwaZulu-Natal', zone: '03B' },
  { town: 'Lower Tugela', district: 'Lower Tugela', province: 'KwaZulu-Natal', zone: '03A' },
  { town: 'Stanger', district: 'Lower Tugela', province: 'KwaZulu-Natal', zone: '03A' },
  { town: 'Lower Umfolozi', district: 'Lower Umfolozi', province: 'KwaZulu-Natal', zone: '05A' },
  { town: 'Empangeni', district: 'Lower Umfolozi', province: 'KwaZulu-Natal', zone: '05A' },
  { town: 'Lulekani', district: 'Lulekani', province: 'Limpopo', zone: '62C' },
  { town: 'Lydenburg', district: 'Lydenburg', province: 'Mpumalanga', zone: '10C' },
  { town: 'Maclear', district: 'Maclear', province: 'Eastern Cape', zone: '08A' },
  { town: 'Madikwe', district: 'Madikwe', province: 'North West', zone: '10C' },
  { town: 'Mahlabatini', district: 'Mahlabatini', province: 'KwaZulu-Natal', zone: '06A' },
  { town: 'Malamulele', district: 'Malamulele', province: 'Limpopo', zone: '64C' },
  { town: 'Malmesbury', district: 'Malmesbury', province: 'Western Cape', zone: '03A' },
  { town: 'Matatiele', district: 'Maluki (Matatiele)', province: 'Eastern Cape', zone: '57A' },
  { town: 'Mankwe', district: 'Mankwe', province: 'North West', zone: '10C' },
  { town: 'Mapulaneng', district: 'Mapulaneng', province: 'Limpopo', zone: '61C' },
  { town: 'Mapumulo', district: 'Mapumulo', province: 'KwaZulu-Natal', zone: '03A' },
  { town: 'Marico', district: 'Marico', province: 'North West', zone: '10C' },
  { town: 'Marquard', district: 'Marquard', province: 'Free State', zone: '08C' },
  { town: 'Mbombela', district: 'Nelspruit', province: 'Mpumalanga', zone: '61C' },
  { town: 'Nelspruit', district: 'Nelspruit', province: 'Mpumalanga', zone: '61C' },
  { town: 'White River', district: 'White River', province: 'Mpumalanga', zone: '61C' },
  { town: 'Middelburg', district: 'Middelburg (MP)', province: 'Mpumalanga', zone: '10C' },
  { town: 'eMalahleni', district: 'Witbank', province: 'Mpumalanga', zone: '09C' },
  { town: 'Witbank', district: 'Witbank', province: 'Mpumalanga', zone: '09C' },
  { town: 'Secunda', district: 'Secunda', province: 'Mpumalanga', zone: '09C' },
  { town: 'Mitchells Plain', district: 'Mitchells Plain', province: 'Western Cape', zone: '01A' },
  { town: 'Khayelitsha', district: 'Mitchells Plain', province: 'Western Cape', zone: '01A' },
  { town: 'Montagu', district: 'Montagu', province: 'Western Cape', zone: '05A' },
  { town: 'Ashton', district: 'Montagu', province: 'Western Cape', zone: '05A' },
  { town: 'Bonnievale', district: 'Montagu', province: 'Western Cape', zone: '05A' },
  { town: 'Mooirivier', district: 'Mooirivier', province: 'KwaZulu-Natal', zone: '05B' },
  { town: 'Moorreesburg', district: 'Moorreesburg', province: 'Western Cape', zone: '04A' },
  { town: 'Mossel Bay', district: 'Mossel Bay', province: 'Western Cape', zone: '01A' },
  { town: 'Mount Currie', district: 'Mount Currie', province: 'KwaZulu-Natal', zone: '57A' },
  { town: 'Kokstad', district: 'Mount Currie', province: 'KwaZulu-Natal', zone: '57A' },
  { town: 'Musina', district: 'Musina (Messina)', province: 'Limpopo', zone: '14C' },
  { town: 'Messina', district: 'Musina (Messina)', province: 'Limpopo', zone: '14C' },
  { town: 'Naphuno', district: 'Naphuno', province: 'Limpopo', zone: '63C' },
  { town: 'Namakwaland', district: 'Namakwaland', province: 'Northern Cape', zone: '31J' },
  { town: 'Port Nolloth', district: 'Namakwaland Port Nolloth', province: 'Northern Cape', zone: '35J' },
  { town: 'Springbok', district: 'Namakwaland South', province: 'Northern Cape', zone: '31J' },
  { town: 'Ndwedwe', district: 'Ndwedwe', province: 'KwaZulu-Natal', zone: '02A' },
  { town: 'Nebo', district: 'Nebo', province: 'Limpopo', zone: '11C' },
  { town: 'New Hanover', district: 'New Hanover', province: 'KwaZulu-Natal', zone: '03B' },
  { town: 'Newcastle', district: 'Newcastle', province: 'KwaZulu-Natal', zone: '06C' },
  { town: 'Ngotshe', district: 'Ngotshe', province: 'KwaZulu-Natal', zone: '57A' },
  { town: 'Nigel', district: 'Nigel', province: 'Gauteng', zone: '09C' },
  { town: 'Nkandla', district: 'Nkandla', province: 'KwaZulu-Natal', zone: '05A' },
  { town: 'Nkomazi', district: 'Nkomazi (Kamhulshwa)', province: 'Mpumalanga', zone: '61C' },
  { town: 'Nongoma', district: 'Nongoma', province: 'KwaZulu-Natal', zone: '06A' },
  { town: 'Ulundi', district: 'Nongoma', province: 'KwaZulu-Natal', zone: '06A' },
  { town: 'Noupoort', district: 'Noupoort', province: 'Northern Cape', zone: '07A' },
  { town: 'Nqutu', district: 'Nqutu', province: 'KwaZulu-Natal', zone: '06C' },
  { town: 'Nsikazi', district: 'Nsikazi (Kangwane)', province: 'Mpumalanga', zone: '61C' },
  { town: 'Oberholzer', district: 'Oberholzer', province: 'Gauteng', zone: '09C' },
  { town: 'Odendaalsrus', district: 'Odendaalsrus', province: 'Free State', zone: '09C' },
  { town: 'Virginia', district: 'Odendaalsrus', province: 'Free State', zone: '09C' },
  { town: 'Odi', district: 'Odi', province: 'North West', zone: '09C' },
  { town: 'Oudtshoorn', district: 'Oudtshoorn', province: 'Western Cape', zone: '04A' },
  { town: 'De Rust', district: 'Oudtshoorn', province: 'Western Cape', zone: '04A' },
  { town: 'Paarl', district: 'Paarl', province: 'Western Cape', zone: '02A' },
  { town: 'Wellington', district: 'Paarl', province: 'Western Cape', zone: '02A' },
  { town: 'Parys', district: 'Parys', province: 'Free State', zone: '09C' },
  { town: 'Paulpietersburg', district: 'Paulpietersburg', province: 'KwaZulu-Natal', zone: '57C' },
  { town: 'Peddie', district: 'Peddie (Ciskei)', province: 'Eastern Cape', zone: '04A' },
  { town: 'Petrusburg', district: 'Petrusburg', province: 'Free State', zone: '11C' },
  { town: 'Phalaborwa', district: 'Phalaborwa', province: 'Limpopo', zone: '63C' },
  { town: 'Philipstown', district: 'Philipstown', province: 'Northern Cape', zone: '09A' },
  { town: 'Phillippolis', district: 'Phillippolis', province: 'Free State', zone: '08A' },
  { town: 'Piet Retief', district: 'Piet Retief', province: 'Mpumalanga', zone: '58C' },
  { town: 'Pietermaritzburg', district: 'Pietermaritzburg', province: 'KwaZulu-Natal', zone: '03B' },
  { town: 'Piketberg', district: 'Piketberg', province: 'Western Cape', zone: '06B' },
  { town: 'Pilgrims Rest', district: 'Pilgrims Rest', province: 'Mpumalanga', zone: '61C' },
  { town: 'Pinetown', district: 'Pinetown', province: 'KwaZulu-Natal', zone: '01A' },
  { town: 'Polela', district: 'Polela', province: 'KwaZulu-Natal', zone: '05B' },
  { town: 'Polokwane', district: 'Polokwane (Pietersburg)', province: 'Limpopo', zone: '12C' },
  { town: 'Pietersburg', district: 'Polokwane (Pietersburg)', province: 'Limpopo', zone: '12C' },
  { town: 'Port Elizabeth', district: 'Port Elizabeth', province: 'Eastern Cape', zone: '01A' },
  { town: 'Gqeberha', district: 'Port Elizabeth', province: 'Eastern Cape', zone: '01A' },
  { town: 'Port Shepstone', district: 'Port Shepstone', province: 'KwaZulu-Natal', zone: '04A' },
  { town: 'Margate', district: 'Port Shepstone', province: 'KwaZulu-Natal', zone: '04A' },
  { town: 'Postmasburg', district: 'Postmasburg', province: 'Northern Cape', zone: '13C' },
  { town: 'Potchefstroom', district: 'Potchefstroom', province: 'North West', zone: '09C' },
  { town: 'Pretoria', district: 'Pretoria', province: 'Gauteng', zone: '09C' },
  { town: 'Tshwane', district: 'Pretoria', province: 'Gauteng', zone: '09C' },
  { town: 'Centurion', district: 'Pretoria', province: 'Gauteng', zone: '09C' },
  { town: 'Soshanguve', district: 'Soshanguve', province: 'Gauteng', zone: '09C' },
  { town: 'Mamelodi', district: 'Pretoria', province: 'Gauteng', zone: '09C' },
  { town: 'Prieska', district: 'Prieska', province: 'Northern Cape', zone: '09A' },
  { town: 'Prince Albert', district: 'Prince Albert', province: 'Western Cape', zone: '07B' },
  { town: 'Queenstown', district: 'Queenstown', province: 'Eastern Cape', zone: '05A' },
  { town: 'Komani', district: 'Queenstown', province: 'Eastern Cape', zone: '05A' },
  { town: 'Qumbu', district: 'Qumbu', province: 'Eastern Cape', zone: '57A' },
  { town: 'Randburg', district: 'Randburg', province: 'Gauteng', zone: '09C' },
  { town: 'Randfontein', district: 'Randfontein', province: 'Gauteng', zone: '09C' },
  { town: 'Reddersburg', district: 'Reddersburg', province: 'Free State', zone: '08A' },
  { town: 'Reitz', district: 'Reitz', province: 'Free State', zone: '08C' },
  { town: 'Richmond', district: 'Richmond (KZN)', province: 'KwaZulu-Natal', zone: '03A' },
  { town: 'Ritavi', district: 'Ritavi', province: 'Limpopo', zone: '63C' },
  { town: 'Riversdale', district: 'Riversdale', province: 'Western Cape', zone: '04A' },
  { town: 'Stilbaai', district: 'Riversdale', province: 'Western Cape', zone: '04A' },
  { town: 'Albertinia', district: 'Riversdale', province: 'Western Cape', zone: '04A' },
  { town: 'Robertson', district: 'Robertson', province: 'Western Cape', zone: '05A' },
  { town: 'McGregor', district: 'Robertson', province: 'Western Cape', zone: '05A' },
  { town: 'Roodepoort', district: 'Roodepoort', province: 'Gauteng', zone: '09C' },
  { town: 'Rouxville', district: 'Rouxville', province: 'Free State', zone: '08A' },
  { town: 'Rustenburg', district: 'Rustenburg', province: 'North West', zone: '09C' },
  { town: 'Sasolburg', district: 'Sasolburg', province: 'Free State', zone: '09C' },
  { town: 'Schweizer-Reneke', district: 'Schweizer-Reneke', province: 'North West', zone: '11C' },
  { town: 'Senekal', district: 'Senekal', province: 'Free State', zone: '08C' },
  { town: 'Seshego', district: 'Seshego', province: 'Limpopo', zone: '12C' },
  { town: 'Simonstown', district: 'Simonstown', province: 'Western Cape', zone: '01A' },
  { town: 'Smithfield', district: 'Smithfield', province: 'Free State', zone: '08A' },
  { town: 'Somerset East', district: 'Somerset East', province: 'Eastern Cape', zone: '07B' },
  { town: 'Somerset West', district: 'Somerset West', province: 'Western Cape', zone: '02A' },
  { town: 'Strand', district: 'Somerset West', province: 'Western Cape', zone: '02A' },
  { town: "Gordon's Bay", district: 'Somerset West', province: 'Western Cape', zone: '02A' },
  { town: 'Springs', district: 'Springs', province: 'Gauteng', zone: '09C' },
  { town: 'Brakpan', district: 'Brakpan', province: 'Gauteng', zone: '09C' },
  { town: 'Standerton', district: 'Standerton', province: 'Mpumalanga', zone: '08C' },
  { town: 'Stellenbosch', district: 'Stellenbosch', province: 'Western Cape', zone: '02A' },
  { town: 'Franschhoek', district: 'Stellenbosch', province: 'Western Cape', zone: '02A' },
  { town: 'Sterkstroom', district: 'Sterkstroom', province: 'Eastern Cape', zone: '05A' },
  { town: 'Steynsburg', district: 'Steynsburg', province: 'Eastern Cape', zone: '07A' },
  { town: 'Steytlerville', district: 'Steytlerville', province: 'Eastern Cape', zone: '07B' },
  { town: 'Stutterheim', district: 'Stutterheim', province: 'Eastern Cape', zone: '04A' },
  { town: 'Sutherland', district: 'Sutherland', province: 'Northern Cape', zone: '12B' },
  { town: 'Swartruggens', district: 'Swartruggens', province: 'North West', zone: '09C' },
  { town: 'Swellendam', district: 'Swellendam', province: 'Western Cape', zone: '05A' },
  { town: 'Barrydale', district: 'Swellendam', province: 'Western Cape', zone: '05A' },
  { town: 'Tarka', district: 'Tarka', province: 'Eastern Cape', zone: '05A' },
  { town: 'Taung', district: 'Taung', province: 'North West', zone: '11C' },
  { town: 'Thabamoopo', district: 'Thabamoopo', province: 'Limpopo', zone: '12C' },
  { town: 'Mokopane', district: 'Mokopane (Potgietersrus)', province: 'Limpopo', zone: '11C' },
  { town: 'Potgietersrus', district: 'Mokopane (Potgietersrus)', province: 'Limpopo', zone: '11C' },
  { town: 'Thaba\'nchu', district: "Thaba'nchu", province: 'Free State', zone: '11C' },
  { town: 'Thabazimbi', district: 'Thabazimbi', province: 'Limpopo', zone: '12C' },
  { town: 'Theunissen', district: 'Theunissen', province: 'Free State', zone: '10C' },
  { town: 'Thohoyandou', district: 'Thohoyandou', province: 'Limpopo', zone: '13C' },
  { town: 'Trompsburg', district: 'Trompsburg', province: 'Free State', zone: '08A' },
  { town: 'Tsolo', district: 'Tsolo', province: 'Eastern Cape', zone: '57A' },
  { town: 'Tsomo', district: 'Tsomo', province: 'Eastern Cape', zone: '05A' },
  { town: 'Tulbagh', district: 'Tulbagh', province: 'Western Cape', zone: '04A' },
  { town: 'Wolseley', district: 'Tulbagh', province: 'Western Cape', zone: '04A' },
  { town: 'Ubombo', district: 'Ubombo', province: 'KwaZulu-Natal', zone: '57A' },
  { town: 'Uitenhage', district: 'Uitenhage', province: 'Eastern Cape', zone: '02A' },
  { town: 'Despatch', district: 'Uitenhage', province: 'Eastern Cape', zone: '02A' },
  { town: 'Umbumbulu', district: 'Umbumbulu', province: 'KwaZulu-Natal', zone: '02A' },
  { town: 'Umlazi', district: 'Umlazi', province: 'KwaZulu-Natal', zone: '01A' },
  { town: 'Mthatha', district: 'Umtata', province: 'Eastern Cape', zone: '06A' },
  { town: 'Umtata', district: 'Umtata', province: 'Eastern Cape', zone: '06A' },
  { town: 'Umvoti', district: 'Umvoti', province: 'KwaZulu-Natal', zone: '05B' },
  { town: 'Umzimkulu', district: 'Umzimkulu', province: 'Eastern Cape', zone: '05A' },
  { town: 'Umzinto', district: 'Umzinto', province: 'KwaZulu-Natal', zone: '03A' },
  { town: 'Underberg', district: 'Underberg', province: 'KwaZulu-Natal', zone: '05B' },
  { town: 'Uniondale', district: 'Uniondale', province: 'Western Cape', zone: '06B' },
  { town: 'Utrecht', district: 'Utrecht', province: 'KwaZulu-Natal', zone: '57C' },
  { town: 'Van Rhynsdorp', district: 'Van Rhynsdorp', province: 'Western Cape', zone: '09B' },
  { town: 'Vredendal', district: 'Van Rhynsdorp', province: 'Western Cape', zone: '09B' },
  { town: 'Vanderbijlpark', district: 'Vanderbijlpark', province: 'Gauteng', zone: '09C' },
  { town: 'Evaton', district: 'Vanderbijlpark', province: 'Gauteng', zone: '09C' },
  { town: 'Ventersburg', district: 'Ventersburg', province: 'Free State', zone: '08C' },
  { town: 'Ventersdorp', district: 'Ventersdorp', province: 'North West', zone: '10C' },
  { town: 'Venterstad', district: 'Venterstad', province: 'Eastern Cape', zone: '08A' },
  { town: 'Vereeniging', district: 'Vereeniging', province: 'Gauteng', zone: '09C' },
  { town: 'Victoria East', district: 'Victoria East', province: 'Eastern Cape', zone: '04A' },
  { town: 'Alice', district: 'Victoria East', province: 'Eastern Cape', zone: '04A' },
  { town: 'Victoria West', district: 'Victoria West', province: 'Northern Cape', zone: '12B' },
  { town: 'Viljoenskroon', district: 'Viljoenskroon', province: 'Free State', zone: '09C' },
  { town: 'Volksrust', district: 'Volksrust', province: 'Mpumalanga', zone: '57C' },
  { town: 'Vrede', district: 'Vrede', province: 'Free State', zone: '08C' },
  { town: 'Vredefort', district: 'Vredefort', province: 'Free State', zone: '09C' },
  { town: 'Vredenburg', district: 'Vredenburg', province: 'Western Cape', zone: '05A' },
  { town: 'Vryburg', district: 'Vryburg', province: 'North West', zone: '12C' },
  { town: 'Vryheid', district: 'Vryheid', province: 'KwaZulu-Natal', zone: '06C' },
  { town: 'Vuwani', district: 'Vuwani', province: 'Limpopo', zone: '13C' },
  { town: 'Wakkerstroom', district: 'Wakkerstroom', province: 'Mpumalanga', zone: '58C' },
  { town: 'Warrenton', district: 'Warrenton', province: 'Northern Cape', zone: '11C' },
  { town: 'Waterberg', district: 'Waterberg', province: 'Limpopo', zone: '11C' },
  { town: 'Weenen', district: 'Weenen', province: 'KwaZulu-Natal', zone: '05B' },
  { town: 'Welkom', district: 'Welkom', province: 'Free State', zone: '09C' },
  { town: 'Wellington', district: 'Wellington', province: 'Western Cape', zone: '02A' },
  { town: 'Wepener', district: 'Wepener', province: 'Free State', zone: '08A' },
  { town: 'Wesselsbron', district: 'Wesselsbron', province: 'Free State', zone: '09C' },
  { town: 'Westonaria', district: 'Westonaria', province: 'Gauteng', zone: '09C' },
  { town: 'Williston', district: 'Williston', province: 'Northern Cape', zone: '10B' },
  { town: 'Willowmore', district: 'Willowmore', province: 'Eastern Cape', zone: '07B' },
  { town: 'Winburg', district: 'Winburg', province: 'Free State', zone: '10C' },
  { town: 'Witsieshoek', district: 'Witsieshoek', province: 'Free State', zone: '07C' },
  { town: 'Phuthaditjhaba', district: 'Witsieshoek', province: 'Free State', zone: '07C' },
  { town: 'Wolmaranstad', district: 'Wolmaranstad', province: 'North West', zone: '10C' },
  { town: 'Mahikeng', district: 'Mafikeng', province: 'North West', zone: '12C' },
  { town: 'Mafikeng', district: 'Mafikeng', province: 'North West', zone: '12C' },
  { town: 'Lichtenburg', district: 'Lichtenburg', province: 'North West', zone: '10C' },
  { town: 'Zeerust', district: 'Zeerust', province: 'North West', zone: '10C' },
  { town: 'Worcester', district: 'Worcester', province: 'Western Cape', zone: '05A' },
  { town: 'Rawsonville', district: 'Worcester', province: 'Western Cape', zone: '05A' },
  { town: 'Wynberg', district: 'Wynberg', province: 'Western Cape', zone: '01A' },
  { town: 'Xalanga', district: 'Xalanga', province: 'Eastern Cape', zone: '07A' },
  { town: 'Zastron', district: 'Zastron', province: 'Free State', zone: '08A' },
  { town: 'Zwelitsha', district: 'Zwelitsha', province: 'Eastern Cape', zone: '03A' },
  { town: 'Bisho', district: 'Zwelitsha', province: 'Eastern Cape', zone: '03A' },
  { town: 'Makhanda', district: 'Albany', province: 'Eastern Cape', zone: '04A' },
  { town: 'Grahamstown', district: 'Albany', province: 'Eastern Cape', zone: '04A' },
  { town: 'Richards Bay', district: 'Lower Umfolozi', province: 'KwaZulu-Natal', zone: '05A' },
  { town: 'Ballito', district: 'Lower Tugela', province: 'KwaZulu-Natal', zone: '03A' },
  { town: 'Umhlanga', district: 'Durban', province: 'KwaZulu-Natal', zone: '01A' },
  { town: 'Amanzimtoti', district: 'Durban', province: 'KwaZulu-Natal', zone: '01A' },
  { town: 'Hartenbos', district: 'Mossel Bay', province: 'Western Cape', zone: '01A' },
  { town: 'Napier', district: 'Bredasdorp', province: 'Western Cape', zone: '06A' },
  { town: 'Grabouw', district: 'Caledon', province: 'Western Cape', zone: '05A' },
  { town: 'Wilderness', district: 'George', province: 'Western Cape', zone: '03A' },
  { town: 'Darling', district: 'Malmesbury', province: 'Western Cape', zone: '03A' },
  { town: 'Velddrif', district: 'Piketberg', province: 'Western Cape', zone: '06B' },
  { town: 'Prince Alfred Hamlet', district: 'Ceres', province: 'Western Cape', zone: '05A' },
  { town: 'Villiersdorp', district: 'Villiersdorp', province: 'Western Cape', zone: '05A' },
  { town: 'Komatipoort', district: 'Komatipoort', province: 'Mpumalanga', zone: '61C' },
  { town: 'Hazyview', district: 'Nelspruit', province: 'Mpumalanga', zone: '61C' },
  { town: 'Matjiesfontein', district: 'Laingsburg', province: 'Western Cape', zone: '07B' },
  { town: 'Burgersfort', district: 'Lydenburg', province: 'Limpopo', zone: '10C' },
  { town: 'Marble Hall', district: 'Marble Hall', province: 'Limpopo', zone: '10C' },
  { town: 'Modimolle', district: 'Nylstroom', province: 'Limpopo', zone: '10C' },
  { town: 'Nylstroom', district: 'Nylstroom', province: 'Limpopo', zone: '10C' },
  { town: 'Benoni', district: 'Benoni', province: 'Gauteng', zone: '09C' },
  { town: 'Orkney', district: 'Klerksdorp', province: 'North West', zone: '09C' },
  { town: 'Evander', district: 'Evander', province: 'Mpumalanga', zone: '09C' },
  { town: 'Balfour (MP)', district: 'Balfour', province: 'Mpumalanga', zone: '09C' },
  { town: 'Bethal (MP)', district: 'Bethal', province: 'Mpumalanga', zone: '09C' },
];

export function lookupZone(townOrDistrict: string): PriceZoneRef | null {
  const q = townOrDistrict.trim().toLowerCase();
  return (
    PRICE_ZONE_REFS.find(r => r.town.toLowerCase() === q || r.district.toLowerCase() === q) ?? null
  );
}

export function downloadZoneReference(): void {
  const header = 'Town/Area,Magisterial District,Province,DMRE Zone Code\n';
  const rows = PRICE_ZONE_REFS.map(r =>
    `"${r.town}","${r.district}","${r.province}","${r.zone}"`
  ).join('\n');
  const blob = new Blob([header + rows], { type: 'text/csv' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = 'sa_dmre_fuel_price_zones_reference.csv';
  a.click();
  URL.revokeObjectURL(url);
}
