import { useState } from 'react';
import { X, Mail, Send, Loader2 } from 'lucide-react';
import { supabase } from '../lib/supabase';

interface EmailReportModalProps {
  open: boolean;
  onClose: () => void;
  reportName: string;
  dateRange: string;
  csvContent: string;
}

function base64Encode(str: string): string {
  const bytes = new TextEncoder().encode(str);
  let binary = '';
  for (let i = 0; i < bytes.length; i++) {
    binary += String.fromCharCode(bytes[i]);
  }
  return btoa(binary);
}

function sanitizeFilename(name: string): string {
  return name.replace(/[^a-zA-Z0-9_\- ]/g, '').trim().replace(/\s+/g, '_');
}

export default function EmailReportModal({ open, onClose, reportName, dateRange, csvContent }: EmailReportModalProps) {
  const [to, setTo] = useState('');
  const [subject, setSubject] = useState(`MyFuelApp.net - ${reportName}`);
  const [sending, setSending] = useState(false);
  const [message, setMessage] = useState('');
  const [success, setSuccess] = useState(false);

  if (!open) return null;

  const handleSend = async () => {
    if (!to.trim()) {
      setMessage('Please enter at least one email address');
      return;
    }

    setSending(true);
    setMessage('');
    setSuccess(false);

    try {
      const textBody = `MyFuelApp.net - ${reportName}\n${dateRange}\n\nPlease find the report attached as a CSV file.\n\nThis report was generated by MyFuelApp.net`;

      const filename = `${sanitizeFilename(reportName)}_report.csv`;
      const attachment = {
        filename,
        content: base64Encode(csvContent),
      };

      const { data, error } = await supabase.functions.invoke('send-email', {
        body: {
          to: to.split(',').map((e) => e.trim()).filter(Boolean),
          subject,
          text: textBody,
          attachments: [attachment],
        },
      });

      if (error) throw error;

      if (data?.error) throw new Error(data.error);

      setSuccess(true);
      setMessage('Report emailed successfully');
      setTimeout(() => {
        onClose();
        setSuccess(false);
        setMessage('');
        setTo('');
      }, 2000);
    } catch (err: any) {
      setMessage(err.message || 'Failed to send email');
    } finally {
      setSending(false);
    }
  };

  return (
    <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
      <div className="bg-white rounded-lg shadow-xl max-w-md w-full">
        <div className="flex items-center justify-between px-6 py-4 border-b border-gray-200">
          <div className="flex items-center gap-2">
            <Mail className="w-5 h-5 text-blue-600" />
            <h3 className="text-lg font-semibold text-gray-900">Email Report</h3>
          </div>
          <button onClick={onClose} className="text-gray-400 hover:text-gray-600 transition-colors">
            <X className="w-5 h-5" />
          </button>
        </div>

        <div className="p-6 space-y-4">
          <div>
            <p className="text-sm font-medium text-gray-700 mb-1">Report</p>
            <p className="text-sm text-gray-900">{reportName}</p>
            <p className="text-xs text-gray-500 mt-0.5">{dateRange}</p>
            <p className="text-xs text-blue-600 mt-1">Attached as CSV file</p>
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Recipient Email Address
            </label>
            <input
              type="text"
              value={to}
              onChange={(e) => setTo(e.target.value)}
              placeholder="email@example.com (comma-separate for multiple)"
              className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 text-sm"
              onKeyDown={(e) => e.key === 'Enter' && !sending && handleSend()}
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Subject
            </label>
            <input
              type="text"
              value={subject}
              onChange={(e) => setSubject(e.target.value)}
              className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 text-sm"
            />
          </div>

          {message && (
            <div className={`text-sm p-3 rounded-lg ${success ? 'bg-green-50 text-green-800' : 'bg-red-50 text-red-700'}`}>
              {message}
            </div>
          )}

          <div className="flex justify-end gap-3 pt-2">
            <button
              onClick={onClose}
              className="px-4 py-2 text-sm font-medium text-gray-700 bg-gray-100 rounded-lg hover:bg-gray-200 transition-colors"
            >
              Cancel
            </button>
            <button
              onClick={handleSend}
              disabled={sending || !to.trim()}
              className="flex items-center gap-2 px-4 py-2 text-sm font-medium text-white bg-blue-600 rounded-lg hover:bg-blue-700 disabled:bg-gray-300 disabled:cursor-not-allowed transition-colors"
            >
              {sending ? (
                <Loader2 className="w-4 h-4 animate-spin" />
              ) : (
                <Send className="w-4 h-4" />
              )}
              {sending ? 'Sending...' : 'Send Report'}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
