import { useState } from 'react';
import { X, Mail, Send, Loader2 } from 'lucide-react';
import { supabase } from '../lib/supabase';

interface EmailReportModalProps {
  open: boolean;
  onClose: () => void;
  reportName: string;
  dateRange: string;
  htmlContent: string;
}

export default function EmailReportModal({ open, onClose, reportName, dateRange, htmlContent }: EmailReportModalProps) {
  const [to, setTo] = useState('');
  const [subject, setSubject] = useState(`MyFuelApp.net - ${reportName}`);
  const [sending, setSending] = useState(false);
  const [message, setMessage] = useState('');
  const [success, setSuccess] = useState(false);

  if (!open) return null;

  const handleSend = async () => {
    if (!to.trim()) {
      setMessage('Please enter at least one email address');
      return;
    }

    setSending(true);
    setMessage('');
    setSuccess(false);

    try {
      const fullHtml = `
        <div style="font-family: Arial, Helvetica, sans-serif; max-width: 900px; margin: 0 auto; color: #1f2937;">
          <div style="background: #1e40af; color: white; padding: 20px 30px; border-radius: 8px 8px 0 0;">
            <h1 style="margin: 0; font-size: 22px;">MyFuelApp.net</h1>
            <p style="margin: 4px 0 0; font-size: 14px; opacity: 0.9;">${reportName}</p>
          </div>
          <div style="padding: 20px 30px; border: 1px solid #e5e7eb; border-top: none; border-radius: 0 0 8px 8px;">
            <p style="margin: 0 0 16px; font-size: 14px; color: #6b7280;">${dateRange}</p>
            ${htmlContent}
          </div>
          <p style="text-align: center; font-size: 12px; color: #9ca3af; margin-top: 20px;">
            This report was generated by MyFuelApp.net
          </p>
        </div>
      `;

      const { data, error } = await supabase.functions.invoke('send-email', {
        body: {
          to: to.split(',').map((e) => e.trim()).filter(Boolean),
          subject,
          html: fullHtml,
        },
      });

      if (error) throw error;

      if (data?.error) throw new Error(data.error);

      setSuccess(true);
      setMessage('Report emailed successfully');
      setTimeout(() => {
        onClose();
        setSuccess(false);
        setMessage('');
        setTo('');
      }, 2000);
    } catch (err: any) {
      setMessage(err.message || 'Failed to send email');
    } finally {
      setSending(false);
    }
  };

  return (
    <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
      <div className="bg-white rounded-lg shadow-xl max-w-md w-full">
        <div className="flex items-center justify-between px-6 py-4 border-b border-gray-200">
          <div className="flex items-center gap-2">
            <Mail className="w-5 h-5 text-blue-600" />
            <h3 className="text-lg font-semibold text-gray-900">Email Report</h3>
          </div>
          <button onClick={onClose} className="text-gray-400 hover:text-gray-600 transition-colors">
            <X className="w-5 h-5" />
          </button>
        </div>

        <div className="p-6 space-y-4">
          <div>
            <p className="text-sm font-medium text-gray-700 mb-1">Report</p>
            <p className="text-sm text-gray-900">{reportName}</p>
            <p className="text-xs text-gray-500 mt-0.5">{dateRange}</p>
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Recipient Email Address
            </label>
            <input
              type="text"
              value={to}
              onChange={(e) => setTo(e.target.value)}
              placeholder="email@example.com (comma-separate for multiple)"
              className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 text-sm"
              onKeyDown={(e) => e.key === 'Enter' && !sending && handleSend()}
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Subject
            </label>
            <input
              type="text"
              value={subject}
              onChange={(e) => setSubject(e.target.value)}
              className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 text-sm"
            />
          </div>

          {message && (
            <div className={`text-sm p-3 rounded-lg ${success ? 'bg-green-50 text-green-800' : 'bg-red-50 text-red-700'}`}>
              {message}
            </div>
          )}

          <div className="flex justify-end gap-3 pt-2">
            <button
              onClick={onClose}
              className="px-4 py-2 text-sm font-medium text-gray-700 bg-gray-100 rounded-lg hover:bg-gray-200 transition-colors"
            >
              Cancel
            </button>
            <button
              onClick={handleSend}
              disabled={sending || !to.trim()}
              className="flex items-center gap-2 px-4 py-2 text-sm font-medium text-white bg-blue-600 rounded-lg hover:bg-blue-700 disabled:bg-gray-300 disabled:cursor-not-allowed transition-colors"
            >
              {sending ? (
                <Loader2 className="w-4 h-4 animate-spin" />
              ) : (
                <Send className="w-4 h-4" />
              )}
              {sending ? 'Sending...' : 'Send Report'}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
