-- =============================================================================
-- Definitive fix: revoke EXECUTE from PUBLIC on all SECURITY DEFINER functions
-- The previous migration only revoked from anon/authenticated but left the
-- PUBLIC grant intact. PUBLIC grants access to ALL roles including anon.
-- We revoke from PUBLIC, then explicitly re-grant only where needed.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- REVOKE from PUBLIC on all flagged SECURITY DEFINER functions
-- -----------------------------------------------------------------------------
REVOKE EXECUTE ON FUNCTION public.acquire_transaction_lock(uuid, uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.acquire_transaction_lock(uuid, text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.allocate_payment(uuid, jsonb) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.apply_late_payment_interest() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.auto_generate_fuel_transaction_invoice() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.auto_grant_main_user_permissions() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.auto_grant_permissions_for_main_users() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.auto_grant_permissions_to_secondary_main_user() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.auto_match_bank_transactions(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.belongs_to_organization(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.calculate_statement_totals(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.can_manage_driver_payment_settings(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.can_manage_organization_users(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.can_view_organization_users(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.check_driver_spending_limit(uuid, numeric) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.check_fuel_transaction_invoice_integrity() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.check_fuel_transaction_invoice_integrity(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.check_garage_account_limit(uuid, uuid, numeric) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.check_max_items_per_transaction() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.check_organization_spending_limit(uuid, numeric) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.check_vehicle_drawn_by_driver(uuid, uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.check_vehicle_not_already_drawn() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.complete_client_signup(uuid, text, text, text, text, text, text, text, text, text, text, text, text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.complete_client_signup(uuid, text, text, text, text, text, text, text, text, text, text, text, text, text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.complete_nfc_payment(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.create_driver_payment_settings() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.create_garage_user(uuid, text, text, text, text, text, text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.create_garage_with_organization(jsonb, text, text, text, text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.exec_sql(text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.expire_old_mandates() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.fail_nfc_payment_fallback_to_eft(uuid, text, text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.generate_debit_order_batch(date, date) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.generate_debit_order_run_number() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.generate_fuel_invoice_number() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.generate_garage_statement_number(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.generate_invoice_number() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.generate_monthly_invoices(date) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.generate_payment_number(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.generate_payment_number(uuid, uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.get_driver_current_spending(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.get_invoice_integrity_stats() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.get_next_credit_note_number() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.get_next_invoice_number() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.get_statement_invoices(uuid, uuid, date, date) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.get_statement_payments(uuid, uuid, date, date) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.handle_new_user() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.has_valid_debit_order_mandate(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.increment_driver_spending(uuid, numeric, date) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.is_client_organization(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.is_management_org_user() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.is_management_org_user(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.is_management_organization(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.link_garage_user_to_organization(uuid, uuid, text, text, text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.mark_debit_orders_submitted(uuid[], timestamptz) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.process_credit_control() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.process_debit_order_results(uuid, boolean, text, text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.public_garage_signup(jsonb) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.retry_failed_payments() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.suggest_payment_matches(uuid, integer) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.sync_is_garage_managed() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.sync_title_with_flags() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.sync_user_title_with_flags() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.toggle_secondary_main_user(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.transfer_main_user(uuid, uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.update_credit_notes_updated_at() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.update_invoice_amounts_after_payment() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.update_invoice_totals(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.update_organization_garage_accounts_updated_at() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.update_payment_allocation_amounts() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.uppercase_registration_number() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.user_can_access_mandate(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.user_can_see_organization(uuid, uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.validate_id_number_dob() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.validate_id_number_dob(text, date) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.validate_management_org_no_driver_role() FROM PUBLIC;

-- Also revoke any remaining explicit anon grants (belt and suspenders)
REVOKE EXECUTE ON FUNCTION public.acquire_transaction_lock(uuid, uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.acquire_transaction_lock(uuid, text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.allocate_payment(uuid, jsonb) FROM anon;
REVOKE EXECUTE ON FUNCTION public.complete_nfc_payment(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.fail_nfc_payment_fallback_to_eft(uuid, text, text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.generate_debit_order_batch(date, date) FROM anon;
REVOKE EXECUTE ON FUNCTION public.generate_debit_order_run_number() FROM anon;
REVOKE EXECUTE ON FUNCTION public.generate_garage_statement_number(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.generate_payment_number(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.generate_payment_number(uuid, uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_driver_current_spending(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_next_credit_note_number() FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_statement_invoices(uuid, uuid, date, date) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_statement_payments(uuid, uuid, date, date) FROM anon;
REVOKE EXECUTE ON FUNCTION public.link_garage_user_to_organization(uuid, uuid, text, text, text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.mark_debit_orders_submitted(uuid[], timestamptz) FROM anon;
REVOKE EXECUTE ON FUNCTION public.process_debit_order_results(uuid, boolean, text, text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.suggest_payment_matches(uuid, integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.toggle_secondary_main_user(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.transfer_main_user(uuid, uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.update_invoice_totals(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.user_can_access_mandate(uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.user_can_see_organization(uuid, uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.validate_id_number_dob(text, date) FROM anon;

-- -----------------------------------------------------------------------------
-- Re-grant EXECUTE to authenticated for functions called by the frontend
-- -----------------------------------------------------------------------------

-- Called by authenticated users via the app UI
GRANT EXECUTE ON FUNCTION public.allocate_payment(uuid, jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.auto_match_bank_transactions(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.belongs_to_organization(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.calculate_statement_totals(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.can_manage_driver_payment_settings(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.can_manage_organization_users(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.can_view_organization_users(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.check_driver_spending_limit(uuid, numeric) TO authenticated;
GRANT EXECUTE ON FUNCTION public.check_fuel_transaction_invoice_integrity(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.check_garage_account_limit(uuid, uuid, numeric) TO authenticated;
GRANT EXECUTE ON FUNCTION public.check_organization_spending_limit(uuid, numeric) TO authenticated;
GRANT EXECUTE ON FUNCTION public.check_vehicle_drawn_by_driver(uuid, uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.complete_client_signup(uuid, text, text, text, text, text, text, text, text, text, text, text, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.complete_client_signup(uuid, text, text, text, text, text, text, text, text, text, text, text, text, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.complete_nfc_payment(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.create_garage_user(uuid, text, text, text, text, text, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.create_garage_with_organization(jsonb, text, text, text, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.fail_nfc_payment_fallback_to_eft(uuid, text, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.generate_debit_order_batch(date, date) TO authenticated;
GRANT EXECUTE ON FUNCTION public.generate_debit_order_run_number() TO authenticated;
GRANT EXECUTE ON FUNCTION public.generate_garage_statement_number(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.generate_payment_number(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.generate_payment_number(uuid, uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_driver_current_spending(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_invoice_integrity_stats() TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_next_credit_note_number() TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_statement_invoices(uuid, uuid, date, date) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_statement_payments(uuid, uuid, date, date) TO authenticated;
GRANT EXECUTE ON FUNCTION public.has_valid_debit_order_mandate(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_client_organization(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_management_org_user() TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_management_org_user(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_management_organization(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.link_garage_user_to_organization(uuid, uuid, text, text, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.mark_debit_orders_submitted(uuid[], timestamptz) TO authenticated;
GRANT EXECUTE ON FUNCTION public.process_debit_order_results(uuid, boolean, text, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.suggest_payment_matches(uuid, integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.toggle_secondary_main_user(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.transfer_main_user(uuid, uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.update_invoice_totals(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.user_can_access_mandate(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.user_can_see_organization(uuid, uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.validate_id_number_dob(text, date) TO authenticated;
GRANT EXECUTE ON FUNCTION public.acquire_transaction_lock(uuid, uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.acquire_transaction_lock(uuid, text) TO authenticated;

-- public_garage_signup must remain callable by anon (garage self-registration before login)
GRANT EXECUTE ON FUNCTION public.public_garage_signup(jsonb) TO anon;
GRANT EXECUTE ON FUNCTION public.public_garage_signup(jsonb) TO authenticated;

-- service_role always needs access for edge functions and triggers
GRANT EXECUTE ON FUNCTION public.acquire_transaction_lock(uuid, uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.acquire_transaction_lock(uuid, text) TO service_role;
GRANT EXECUTE ON FUNCTION public.allocate_payment(uuid, jsonb) TO service_role;
GRANT EXECUTE ON FUNCTION public.apply_late_payment_interest() TO service_role;
GRANT EXECUTE ON FUNCTION public.auto_generate_fuel_transaction_invoice() TO service_role;
GRANT EXECUTE ON FUNCTION public.auto_grant_main_user_permissions() TO service_role;
GRANT EXECUTE ON FUNCTION public.auto_grant_permissions_for_main_users() TO service_role;
GRANT EXECUTE ON FUNCTION public.auto_grant_permissions_to_secondary_main_user() TO service_role;
GRANT EXECUTE ON FUNCTION public.auto_match_bank_transactions(uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.belongs_to_organization(uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.calculate_statement_totals(uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.can_manage_driver_payment_settings(uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.can_manage_organization_users(uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.can_view_organization_users(uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.check_driver_spending_limit(uuid, numeric) TO service_role;
GRANT EXECUTE ON FUNCTION public.check_fuel_transaction_invoice_integrity() TO service_role;
GRANT EXECUTE ON FUNCTION public.check_fuel_transaction_invoice_integrity(uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.check_garage_account_limit(uuid, uuid, numeric) TO service_role;
GRANT EXECUTE ON FUNCTION public.check_max_items_per_transaction() TO service_role;
GRANT EXECUTE ON FUNCTION public.check_organization_spending_limit(uuid, numeric) TO service_role;
GRANT EXECUTE ON FUNCTION public.check_vehicle_drawn_by_driver(uuid, uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.check_vehicle_not_already_drawn() TO service_role;
GRANT EXECUTE ON FUNCTION public.complete_client_signup(uuid, text, text, text, text, text, text, text, text, text, text, text, text) TO service_role;
GRANT EXECUTE ON FUNCTION public.complete_client_signup(uuid, text, text, text, text, text, text, text, text, text, text, text, text, text) TO service_role;
GRANT EXECUTE ON FUNCTION public.complete_nfc_payment(uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.create_driver_payment_settings() TO service_role;
GRANT EXECUTE ON FUNCTION public.create_garage_user(uuid, text, text, text, text, text, text) TO service_role;
GRANT EXECUTE ON FUNCTION public.create_garage_with_organization(jsonb, text, text, text, text) TO service_role;
GRANT EXECUTE ON FUNCTION public.exec_sql(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.expire_old_mandates() TO service_role;
GRANT EXECUTE ON FUNCTION public.fail_nfc_payment_fallback_to_eft(uuid, text, text) TO service_role;
GRANT EXECUTE ON FUNCTION public.generate_debit_order_batch(date, date) TO service_role;
GRANT EXECUTE ON FUNCTION public.generate_debit_order_run_number() TO service_role;
GRANT EXECUTE ON FUNCTION public.generate_fuel_invoice_number() TO service_role;
GRANT EXECUTE ON FUNCTION public.generate_garage_statement_number(uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.generate_invoice_number() TO service_role;
GRANT EXECUTE ON FUNCTION public.generate_monthly_invoices(date) TO service_role;
GRANT EXECUTE ON FUNCTION public.generate_payment_number(uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.generate_payment_number(uuid, uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.get_driver_current_spending(uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.get_invoice_integrity_stats() TO service_role;
GRANT EXECUTE ON FUNCTION public.get_next_credit_note_number() TO service_role;
GRANT EXECUTE ON FUNCTION public.get_next_invoice_number() TO service_role;
GRANT EXECUTE ON FUNCTION public.get_statement_invoices(uuid, uuid, date, date) TO service_role;
GRANT EXECUTE ON FUNCTION public.get_statement_payments(uuid, uuid, date, date) TO service_role;
GRANT EXECUTE ON FUNCTION public.handle_new_user() TO service_role;
GRANT EXECUTE ON FUNCTION public.has_valid_debit_order_mandate(uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.increment_driver_spending(uuid, numeric, date) TO service_role;
GRANT EXECUTE ON FUNCTION public.is_client_organization(uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.is_management_org_user() TO service_role;
GRANT EXECUTE ON FUNCTION public.is_management_org_user(uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.is_management_organization(uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.link_garage_user_to_organization(uuid, uuid, text, text, text) TO service_role;
GRANT EXECUTE ON FUNCTION public.mark_debit_orders_submitted(uuid[], timestamptz) TO service_role;
GRANT EXECUTE ON FUNCTION public.process_credit_control() TO service_role;
GRANT EXECUTE ON FUNCTION public.process_debit_order_results(uuid, boolean, text, text) TO service_role;
GRANT EXECUTE ON FUNCTION public.retry_failed_payments() TO service_role;
GRANT EXECUTE ON FUNCTION public.suggest_payment_matches(uuid, integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.sync_is_garage_managed() TO service_role;
GRANT EXECUTE ON FUNCTION public.sync_title_with_flags() TO service_role;
GRANT EXECUTE ON FUNCTION public.sync_user_title_with_flags() TO service_role;
GRANT EXECUTE ON FUNCTION public.toggle_secondary_main_user(uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.transfer_main_user(uuid, uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.update_credit_notes_updated_at() TO service_role;
GRANT EXECUTE ON FUNCTION public.update_invoice_amounts_after_payment() TO service_role;
GRANT EXECUTE ON FUNCTION public.update_invoice_totals(uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.update_organization_garage_accounts_updated_at() TO service_role;
GRANT EXECUTE ON FUNCTION public.update_payment_allocation_amounts() TO service_role;
GRANT EXECUTE ON FUNCTION public.uppercase_registration_number() TO service_role;
GRANT EXECUTE ON FUNCTION public.user_can_access_mandate(uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.user_can_see_organization(uuid, uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.validate_id_number_dob() TO service_role;
GRANT EXECUTE ON FUNCTION public.validate_id_number_dob(text, date) TO service_role;
GRANT EXECUTE ON FUNCTION public.validate_management_org_no_driver_role() TO service_role;
